const GET_ALL_BOOK_INFO_REQUEST = 'book/GET_ALL_BOOK_INFO_REQUEST';
const GET_ALL_BOOK_INFO_REQUEST_SUCCESS =
  'book/GET_ALL_BOOK_INFO_REQUEST_SUCCESS';
const GET_ALL_BOOK_INFO_REQUEST_FAILURE =
  'book/GET_ALL_BOOK_INFO_REQUEST_FAILURE';

export {
  GET_ALL_BOOK_INFO_REQUEST,
  GET_ALL_BOOK_INFO_REQUEST_SUCCESS,
  GET_ALL_BOOK_INFO_REQUEST_FAILURE,
};
